const fs = require('fs');

const files = [
  'DEPLOYMENT_PACKAGE/CONFIGS/socket-server.js',
  'cloudinary_sync.js',
  'drizzle/schema.ts',
  'fetch_all_cloudinary_assets.js',
  'generate_proposal_pdf.js',
  'import_form_data.js',
  'migrate_to_new_cloudinary.js',
  'restore_public_assets.js',
  'src/app/admin/audit-logs/page.js',
  'src/app/admin/dashboard/page.js',
  'src/app/admin/verifications/page.js',
  'src/app/admission/page.js',
  'src/app/api/admin/audit-logs/route.js',
  'src/app/api/admin/clerks/[id]/route.js',
  'src/app/api/admin/create-clerk/route.js',
  'src/app/api/admin/faculty/interests/route.js',
  'src/app/api/admin/infrastructure/backups/restore/route.js',
  'src/app/api/admin/infrastructure/backups/route.js',
  'src/app/api/admin/infrastructure/config/route.js',
  'src/app/api/admin/infrastructure/storage/route.js',
  'src/app/api/admin/infrastructure/storage/zip/route.js',
  'src/app/api/admin/student-stats/route.js',
  'src/app/api/admin/verifications/stats/route.js',
  'src/app/api/auth/[...nextauth]/route.js',
  'src/app/api/auth/google-complete/route.js',
  'src/app/api/auth/logout/route.js',
  'src/app/api/auth/refresh/route.js',
  'src/app/api/auth/reset-password/[token]/route.js',
  'src/app/api/auth/security-events/route.js',
  'src/app/api/auth/security-notifications/route.js',
  'src/app/api/auth/send-otp/route.js',
  'src/app/api/auth/sessions/revoke-others/route.js',
  'src/app/api/auth/sessions/route.js',
  'src/app/api/bugs/route.js',
  'src/app/api/clerk/academic-calendar/bulk-update/route.js',
  'src/app/api/clerk/admission/bulk-import/route.js',
  'src/app/api/clerk/admission/drafts/[id]/finalize/route.js',
  'src/app/api/clerk/admission/student-requests/route.js',
  'src/app/api/clerk/admission/students/[rollno]/route.js',
  'src/app/api/clerk/admission/students/route.js',
  'src/app/api/clerk/faculty/assignments/route.js',
  'src/app/api/clerk/faculty/attendance/session/route.js',
  'src/app/api/clerk/faculty/attendance/status/route.js',
  'src/app/api/clerk/faculty/current-activity/route.js',
  'src/app/api/clerk/faculty/interests/route.js',
  'src/app/api/clerk/faculty/marks/route.js',
  'src/app/api/clerk/faculty/my-timetable/route.js',
  'src/app/api/clerk/faculty/students/route.js',
  'src/app/api/clerk/hod/branch-config/route.js',
  'src/app/api/clerk/hod/branch-subjects/route.js',
  'src/app/api/clerk/hod/subject-assignments/route.js',
  'src/app/api/clerk/hod/substitutions/route.js',
  'src/app/api/clerk/hod/timetable/route.js',
  'src/app/api/clerk/requests/[request_id]/route.js',
  'src/app/api/clerk/scholarship/application/[application_no]/route.js',
  'src/app/api/clerk/scholarship/search-by-name/route.js',
  'src/app/api/clerk/students/[rollno]/route.js',
  'src/app/api/clerk/students/search/route.js',
  'src/app/api/public/admission/route.js',
  'src/app/api/public/config/route.js',
  'src/app/api/public/heartbeat/route.js',
  'src/app/api/public/system/health/route.js',
  'src/app/api/public/system/storage-alert/route.js',
  'src/app/api/student/[rollno]/route.js',
  'src/app/api/student/academic-info/route.js',
  'src/app/api/student/activity/route.js',
  'src/app/api/student/attendance/active-sessions/route.js',
  'src/app/api/student/attendance/verify/route.js',
  'src/app/api/student/current-activity/route.js',
  'src/app/api/student/requests/download/[request_id]/route.js',
  'src/app/api/student/requests/profile/route.js',
  'src/app/api/student/send-update-email-otp/route.js',
  'src/app/api/student/signature/route.js',
  'src/app/api/student/update-profile/route.js',
  'src/app/api/verify/route.js',
  'src/app/api/webhooks/qstash/bulk-import/route.js',
  'src/app/clerk/faculty/attendance/page.js',
  'src/app/clerk/faculty/marks/page.js',
  'src/app/clerk/scholarship/dashboard/page.js',
  'src/app/clerk/settings/edit-profile/page.js',
  'src/app/developers/page.js',
  'src/app/reset-password/[token]/page.js',
  'src/app/student/academics/page.js',
  'src/app/student/profile/page.js',
  'src/app/student/requests/certificates/ScrollHandler.js',
  'src/app/student/requests/certificates/page.js',
  'src/app/student/requests/verification-required/page.js',
  'src/app/student/settings/edit-profile/page.js',
  'src/app/verify/page.js',
  'src/components/BulkImportStudents.js',
  'src/components/ChangePasswordModal.js',
  'src/components/ClerkStudentManagement.js',
  'src/components/Header-MobileView.js',
  'src/components/Header.js',
  'src/components/LoginPanel.js',
  'src/components/Navbar.js',
  'src/components/NotificationDropdown.js',
  'src/components/RealtimeListener.js',
  'src/components/SearchParamToast.client.js',
  'src/components/SetPasswordModal.js',
  'src/components/Sidebar_legacy.js',
  'src/components/admin/infrastructure/BackupManager.js',
  'src/components/admin/infrastructure/ConfigManager.js',
  'src/components/admin/infrastructure/StorageExplorer.js',
  'src/components/clerk/ClerkTopBar.js',
  'src/components/clerk/certificates/CertificateDashboard.js',
  'src/components/clerk/certificates/FiltersButton.js',
  'src/components/clerk/faculty/AttendanceSheet.js',
  'src/components/clerk/faculty/BranchAnalytics.js',
  'src/components/clerk/faculty/FacultyActivityBar.js',
  'src/components/clerk/faculty/HODConsole.js',
  'src/components/clerk/faculty/MarksEntrySheet.js',
  'src/components/clerk/faculty/MobileAttendanceSheet.js',
  'src/components/clerk/faculty/PersonalSchedule.js',
  'src/components/clerk/faculty/SyllabusManager.js',
  'src/components/clerk/requests/AdmissionModal.js',
  'src/components/clerk/requests/StudentUpdateRequestsPanel.js',
  'src/components/clerk/scholarship/AddEditRecordInstitutionalModal.js',
  'src/context/AcademicsContext.js',
  'src/context/ProfileActivityContext.js',
  'src/lib/providers/storage/LocalStorageProvider.js'
];

files.forEach(f => {
  if (!fs.existsSync(f)) return;
  let text = fs.readFileSync(f, 'utf8');
  
  // Replace console.log with console.info
  text = text.replace(/console\.log\(/g, 'console.info(');

  // Replace empty blocks { } with { /* empty */ }
  text = text.replace(/\{\s*\}/g, '{ /* empty */ }');
  
  // Replace obj.hasOwnProperty(prop)
  text = text.replace(/([a-zA-Z0-9_]+)\.hasOwnProperty\(([^)]+)\)/g, 'Object.prototype.hasOwnProperty.call($1, $2)');
  
  // Remove unnecessary escape characters (simple heuristic)
  text = text.replace(/\\"/g, '"');
  text = text.replace(/\\\//g, '/');

  fs.writeFileSync(f, text);
});

console.info('Fixed syntax issues.');
