export const semester4 = [
  {
    "code": "ME-220",
    "title": "Thermal Engineering",
    "units": [
      { "name": "UNIT-I", "topics": ["Reciprocating Air Compressors: Classification and applications. Ideal and actual P-V diagrams, work input and efficiency relations for single and multi stage compressors. Effect of clearance volume on work input and efficiency. Inter cooling and after cooling concepts."] },
      { "name": "UNIT-II", "topics": ["Internal Combustion Engines: Classification and applications. Working principles of four stroke and two stroke engines, Spark Ignition and Compression ignition engines. Deviation of actual cycles from Air Standard cycles. Performance parameters of I.C. Engines. Heat balance sheet of I. C. Engine. Overview of Engine supporting systems- Cooling Systems, Lubrication systems- Wet sump, Dry sump and Mist Systems. Working principles of S.I. Engine fuel systems- Carburetors, Battery and Magneto Ignition systems. Working principles of C.I. Engine fuel systems- Fuel pump and Fuel injector."] },
      { "name": "UNIT-III", "topics": ["I.C. Engine Combustion phenomena: Stages of combustion in S.I. Engines- Ignition delay, Flame front propagation and After burning. Abnormal combustion- Pre-ignition and Knocking. Factors affecting Knocking. Stages of combustion in C.I. Engines, Delay period, Period of Uncontrolled Combustion, Period of Controlled Combustion and After burning. Abnormal Combustion-Knocking. Factors affecting Knocking. Octane and Cetane rating of fuels. Design considerations for combustion chamber and cylinder head. Type of combustion chambers of S.I. engines and C.I. engines."] },
      { "name": "UNIT-IV", "topics": ["Steam Boilers: Classification and Working Principles. Water tube boilers- Babcok & Wilcox and Stirling boilers. Fire tube boilers- Cornish, Cochran, Locomotive and Lancashire boilers. High Pressure boilers / Supercritical boilers: La mont, Benson boiler, Loeffler boiler and Velox boiler. Boiler Mountings and Accessories: Working Principles of Water level indicator, Pressure gauge, Steam stop valve, Feed check valve, Blow-off cock, Fusible plug, Safety valves, Economizers, Superheaters and Steam separator. Steam Condensers: Jet and Surface condensers, Principle of Operation and Applications."] },
      { "name": "UNIT-V", "topics": ["Steam power plant cycles: Carnot and Rankine cycles of operation and their efficiencies. Analysis of Rankine cycle with superheating, reheating and regeneration (Direct and Indirect types). Steam Nozzles: Flow of steam through convergent - divergent nozzles, velocity of steam flowing through the nozzle, mass of steam discharge through the nozzle, condition for maximum discharge, critical pressure ratio and nozzle efficiency. Super saturated expansion of steam through nozzles. General relationship between area, velocity and pressure in Nozzle flow."] }
    ]
  },
  {
    "code": "MC 220",
    "title": "Constitution of India",
    "units": [
      { "name": "UNIT -1", "topics": ["1. Making of Indian Constitution - Constituent Assembly", "2. Historical Perspective of the Constitution of India", "3. Salient Features and characteristics of the Constitution of India"] },
      { "name": "UNIT -2", "topics": ["1. The Fundamental Rights", "2. The Fundamental Duties and their Legal Status", "3. The Directive Principles of State Policy – Their Importance and Implementation"] },
      { "name": "UNIT -3", "topics": ["1. Federal Structure and Distribution of Administrative, Legislative and Financial Powers between the Union and the States", "2. Parliamentary Form of Government in India – The Constitutional Powers and Status of the President of India", "3. Amendment of the Constitutional Provisions and Procedure"] },
      { "name": "UNIT -4", "topics": ["1. The Judiciary", "2. Constitutional and Legal Frame Work for Protection of Environmental in Global and National Level", "3. Corporate Social Responsibility (CSR) International and National Scenario."] }
    ]
  },
  {
    "code": "ME-221",
    "title": "Machine Tools & Metrology",
    "units": [
      { "name": "UNIT–I", "topics": ["Metal cutting: Introduction, elements of cutting process – Geometry of single point tools. Chip formation and types of chips, chip breakers, mechanism of orthogonal cutting, merchant force diagram, cutting force, cutting speed , feed ,depth of cut ,tool life, coolant.", "Engine lathe – Principle of working, types of lathe, specifications. Taper turning– Lathe attachments. Capstan and Turret lathe – Single spindle and multi-spindle automatic lathes – tool layouts."] },
      { "name": "UNIT–II", "topics": ["Drilling and Boring Machines – Principles of working, specifications, types, operations performed; twist drill. Types of Boring machines and applications. Shaping, slotting and planning machines - Principles of working –machining time calculations."] },
      { "name": "UNIT–III", "topics": ["Milling machines – Principles of working – Types of milling machines – Geometry of milling cutters – methods of indexing.", "Grinding – theory of grinding – classification of grinding machines. Types of abrasives, bonds. Selection of a grinding wheel. Lapping, honing and broaching machines, comparison and Constructional features, machining time calculations"] },
      { "name": "UNIT–IV", "topics": ["Limits, fits and tolerances- Unilateral and bilateral tolerance system, hole and shaft basis system. Interchange ability and selective assembly.", "Limit Gauges: Taylor’s principle, Design of GO and NO GO gauges Measurement of angles, Bevel protractor, Sine bar. Measurement of flat surfaces, straight edges, surface plates, optical flat and auto collimator."] },
      { "name": "UNIT–V", "topics": ["Surface Roughness Measurement-Roughness, Waviness. CLA, RMS, Rz Values. Methods of measurement of", "Surface finish- Talysurf. Screw thread measurement, Gear measurement; Machine Tool Alignment Tests on lathe, milling and drilling machines. Coordinate Measuring Machines: Types and Applications of CMM."] }
    ]
  },
  {
    "code": "ME-222",
    "title": "Design of Machine Elements – I",
    "units": [
      { "name": "UNIT-I", "topics": ["Introduction: General considerations in the design of Engineering Materials and their properties – selection –Manufacturing consideration in design. Tolerances and fits –BIS codes of steels.", "Design for static strength: Simple stresses – Combined stresses – Torsional and Bending stresses – Impact stresses – Stress strain relation – Various theories of failure – Factor of safety – Design for strength and rigidity – preferred numbers. The concept of stiffness in tension, bending, torsion and combined situations."] },
      { "name": "UNIT – II", "topics": ["Design for fatigue strength: Stress concentration – Theoretical stress Concentration factor – Fatigue stress concentration factor- Notch Sensitivity – Design for fluctuating stresses – Endurance limit – Estimation of Endurance strength – Gerber’s curve– Modified Goodman’s line–Soderbergs line.", "Eccentric loading: Design of Machine Frames and Brackets under eccentric and flexural loads, Circular bars under axial, torsion and bending loads, equivalent bending and twisting moments."] },
      { "name": "UNIT – III", "topics": ["Riveted, welded joints: Riveted joints- methods of failure of riveted joints-strength equations- efficiency of riveted joints-eccentrically loaded riveted joints.", "Welded joints: Design of fillet welds-axial loads-circular fillet welds under bending, torsion. Welded joints under eccentric loading."] },
      { "name": "UNIT – IV", "topics": ["Keys, cotters and knuckle joints: Design of keys-stresses in keys-cotter joints-spigot and socket, sleeve and cotter, gib and cotter joints-Knuckle joints.", "Bolted joints: Design of bolts with pre-stresses – Design of joints under eccentric loading – locking devices – bolts of uniform strength."] },
      { "name": "UNIT – V", "topics": ["Shafts: Design of solid and hollow shafts for strength and rigidity – Design of shafts for combined bending and axial loads – Shaft sizes – BIS code. Use of internal and external circlips, Gaskets and seals (stationary & rotary).", "Shaft couplings: Rigid couplings – Muff, Split muff and Flange couplings. Flexible couplings – Flange coupling (Modified).", "Mechanical springs: Stresses and deflections of helical springs-Extension-compression springs- springs for static and fatigue loading – natural frequency of helical springs-energy storage capacity-helical tension springs- co-axial springs."] }
    ]
  },
  {
    "code": "ME-223",
    "title": "Instrumentation and Control Systems",
    "units": [
      { "name": "UNIT–I", "topics": ["Definition – Basic principles of measurement – Measurement systems, generalized configuration and functional description of measuring instruments –examples. Static and Dynamic performance characteristics – sources of errors, Classification and elimination of errors.", "Measurement of Displacement: Theory and construction of various transducers to measure displacement – Piezoelectric, Inductive, capacitance, resistance, ionization and Photo electric transducers, Calibration procedures."] },
      { "name": "UNIT–II", "topics": ["Measurement of Temperature: Various Principles of measurement-Classification: Expansion Type: Bimetallic Strip- Liquid in glass Thermometer; Electrical Resistance Type: Thermistor, Thermocouple, RTD; Radiation", "Pyrometry: Optical Pyrometer; Changes in Chemical Phase: Fusible Indicators and Liquid crystals. Measurement of Pressure: Different principles used- Classification: Manometers, Dead weight pressure gauge. Tester (Piston gauge), Bourdon pressure gauges, Bulk modulus pressure gauges; Bellows – Diaphragm gauges. Low-pressure measurement – Thermal conductivity gauges, ionization pressure gauges, Mcleod pressure gauge."] },
      { "name": "UNIT–III", "topics": ["Measurement of Level: Direct methods – Indirect methods – Capacitive, Radioactive, Ultrasonic, Magnetic, Cryogenic Fuel level indicators – Bubbler level indicators.", "Flow measurement: Rotameter, magnetic, Ultrasonic, Turbine flow meter, Hot – wire anemometer, Laser Doppler Anemometer (LDA).", "Measurement of Speed: Mechanical Tachometers, Electrical tachometers, Non- contact type- Stroboscope", "Measurement of Acceleration and Vibration: Different simple instruments – Principles of Seismic instruments –Vibrometer and accelerometer using this principle- Piezo electric accelerometer."] },
      { "name": "UNIT–IV", "topics": ["Stress-Strain measurements: Various types of stress and strain measurements –Selection and installation of metallic strain gauges- electrical strain gauge – gauge factor – method of usage of resistance strain gauge for bending compressive and tensile strains – Temperature compensation techniques, Use of strain gauges for measuring torque, Strain gauge Rosettes.", "Measurement of Humidity: Moisture content of gases, Sling Psychrometer, Absorption Psychrometer, Dew pointmeter."] },
      { "name": "UNIT–V", "topics": ["Measurement of Force, Torque And Power- Elastic force meters, load cells, Torsion meters, Dynamometers.", "Elements of Control Systems: Introduction, Importance – Classification – Open and closed systems Servomechanisms– Examples with block diagrams–Temperature, speed & position control systems."] }
    ]
  },
  {
    "code": "ME-224",
    "title": "Kinematics of Machinery",
    "units": [
      { "name": "UNIT – I", "topics": ["Mechanisms: Elements or Links – Classification – Rigid Link, flexible and fluid link – Types of kinematics pairs –sliding, turning, rolling, screw and spherical pairs – lower and higher pairs – closed and open pairs – constrained motion – completely, partially or successfully and incompletely constrained .", "Mechanism and Machines: Mobility of Mechanisms: Grublers criterion, classification of machines – kinematics chain – inversions of mechanism – inversions of quadric cycle chain, single and double slider crank chains, Mechanical Advantage, Intermittent motion Mechanism, Ratchet & Paul Generca Mechanicsm."] },
      { "name": "UNIT – II", "topics": ["Kinematics: Velocity and acceleration – Motion of link in machine – Determination of Velocity and acceleration –Graphical method – Application of relative velocity method.", "Plane motion of body: Instantaneous center of rotation- centrodes and axodes– Three centers in line theorem –Graphical determination of instantaneous center, determination of angular velocity of points and links by instantaneous center method.", "Kliens construction - Coriolis acceleration - determination of Coriolis component of acceleration", "Analysis of Mechanisms: Analysis of slider crank chain for displacement- velocity and acceleration of slider –Acceleration diagram for a given mechanism."] },
      { "name": "UNIT – III", "topics": ["Straight-line motion mechanisms: Exact and approximate copied and generated types –Peaucellier - Hart - Scott Russel– Grasshopper – Watt -Tchebicheffs and Robert Mechanism -", "Pantographs Steering gears: Conditions for correct steering – Davis Steering gear, Ackerman’s steering gear.", "Hooke’s Joint: Single and double Hooke’s joint –velocity ratio – application – problems."] },
      { "name": "UNIT – IV", "topics": ["Cams: Definitions of cam and followers – their uses – Types of followers and cams – Terminology – Types of follower motion - Uniform velocity, Simple harmonic motion and uniform acceleration and retardation. Maximum velocity and maximum acceleration during outward and return strokes in the above 3 cases.", "Analysis of motion of followers: Tangent cam with Roller follower – circular arc cam with straight, concave and convex flanks."] },
      { "name": "UNIT – V", "topics": ["Higher pair: Friction wheels and toothed gears – types – law of gearing, condition for constant velocity ratio for transmission of motion – velocity of sliding. Forms of teeth, cycloidal and involutes profiles – phenomena of interferences – Methods of interference. Condition for minimum number of teeth to avoid interference – expressions for arc of contact and path of contact of Pinion & Gear and Pinion & Rack Arrangements– Introduction to Helical –Bevel and worm gearing", "Gear Trains: Introduction: Types – Simple – compound and reverted gear trains –Epicyclic gear train. Methods of finding trail value or velocity ratio of Epicyclic gear trains. Selection of gear box - Differential gear for an automobile"] }
      ]
    }
  ];
