export const semester5 = [
  {
    "code": "PC3101ME",
    "title": "Fluid Mechanics & Hydraulic Machines",
    "units": [
      { "name": "UNIT-I", "topics": ["Fluid Properties: Viscosity of liquids. Newtonian and non-Newtonian fluids. Surface tension, capillary effect, vapour pressure and cavitation. Ideal and real fluids, Incompressible and Compressible flows. Stream lines, Path lines.", "Pressures and pressure head: Types of pressures, Pascal’s law of pressure at a point, variation of pressure vertically in a fluid under gravity.", "Static Forces on Surface and Buoyancy:", "Fluid statics, action of fluid pressure on surface, resultant force and centre of pressure on a plane surface under uniform pressure. Equilibrium of floating bodies, stability of a submerged body, stability of floating bodies, determination of metacentric height, position of the metacentre and centre of buoyancy."] },
      { "name": "UNIT-II", "topics": ["Laws of fluid flow – Continuity equation. Derivation of Euler’s and Bernoulli’s equations. Application of Bernoulli’s equations. Flow measuring devices-Venturimeter, Orifice meter and Pitot static tube.", "Viscous Flow: Reynolds number and Reynolds experiment, flow of viscous fluid through circular pipe- Hagen Poiseuille formula.", "Flow through pipes: Head losses in pipes, bends and fittings. Major energy losses, Minor energy losses, Hydraulic gradient and total energy lines, Pipes in series and parallel, Equivalent pipes."] },
      { "name": "UNIT-III", "topics": ["Hydraulic Turbines: Classification and comparison of impulse and reaction turbines. Impulse turbines: Salient features and working details of Pelton wheel installation. Velocity diagrams. Calculation of number of buckets, bucket sizes and power developed. Overall efficiency, speed regulation methods.", "Reaction turbines: Constructional details and working of Francis and Kaplan turbines. Draft tube. Theory, types and efficiency of draft tubes. Velocity diagrams. Power developed and efficiencies, pressure head at inlet of the runner.", "Principles of similarity applied to hydraulic turbines. Unit quantities, specific speed and its significance for turbine selection. Performance and characteristic curves for Pelton wheel, Francis and Kaplan turbines. Governing of turbines. Cavitation effects in reaction turbines and remedial measures. Surge tanks."] },
      { "name": "UNIT-IV", "topics": ["Centrifugal pumps: Working and constructional details of single stage centrifugal pump. Priming – significance and methods of priming. Basic classification of CF pumps. Types of impellers, casings and vane shapes . Simple and multistage pumps and their applications. Series and parallel operation of CF pumps. Manometric head and its importance. Manometric efficiency and other efficiencies. Losses in CF pumps. Velocity diagrams. Cavitation. Unit quantities, specific speed. Performance and characteristic curves."] },
      { "name": "UNIT-V", "topics": ["Reciprocating pumps: Classification, working details, theory and terms used for single and double acting pumps. Effect of acceleration head and friction. Indicator diagrams. Effect of cavitation and limiting suction head on pump speed. Variation of pressure inside pump cylinder during suction and delivery strokes. Work done, power required and efficiency. Functions of air vessels. Work saved and rate of flow from air vessels. Losses and performance curves for reciprocating pumps. Industrial applications. Types of Positive displacement pumps."] }
    ]
  },
  {
    "code": "PC3102ME",
    "title": "Dynamics of Machines",
    "units": [
      { "name": "UNIT-I", "topics": ["Static and Dynamic Force Analysis in Mechanisms: Four link mechanism, slider-crank mechanism, friction, piston effort, crank effort, turning moment on crank shaft, inertia forces in reciprocating engines, turning moment diagrams, fluctuation of speed and energy- Principle of flywheel. Static and Dynamic analysis of planar mechanisms: Graphical and analytical methods, Free body diagrams, Method of superposition, Equivalent offset inertia force."] },
      { "name": "UNIT-II", "topics": ["Force analysis of space mechanisms, inertia matrix, Lagrangian and Newton-Euler formulation.", "Gyroscope: Gyroscopic couple, gyroscopic reaction and gyroscopic effect in shafts, aeroplanes, ships, two and four wheelers and gyroscopic stabilization."] },
      { "name": "UNIT-III", "topics": ["Forces on bearings due to rotating shaft carrying several eccentric rotors, balancing of shafts carrying several rotors, determination of balancing masses from the forces on the bearings shaking forces in a single cylinders engine, partial balancing of reciprocating engine. Balancing of a two cylinder locomotive engine, determination of unbalanced forces and couples."] },
      { "name": "UNIT-IV", "topics": ["Governors: Function of governor, centrifugal governors, working principles of Watt, Porter, Proel, Hartnell governor with auxiliary spring, Wilson-Hartnell type, sensitiveness, isochronism, hunting, effect of friction, coefficient of insensitiveness, controlling force diagrams, stability criteria, effort and power of a governor."] },
      { "name": "UNIT-V", "topics": ["Vibrations: Free and forced vibrations of a spring mass system with damping, vibration isolation and transmissibility, transverse vibrations of shafts- point load, UDL and several point loads, Energy method, Whirling of shafts, torsional vibrations of rotating shafts-two rotor and three rotor systems and geared system. Natural frequencies of two degree freedom linear systems. Nodes in three rotor systems. Modes of vibration, determining natural frequencies by Holzer’s method for multi-rotor systems. Dunkerley’s method , Raleigh’s method."] }
    ]
  },
  {
    "code": "PC3103ME",
    "title": "Machine Design",
    "units": [
      { "name": "Unit-I", "topics": ["Belts: Flat belts-velocity ratio, effect of slip, ratio of tensions, open and cross belts, centrifugal tension, initial tension, condition for maximum power transmission, design of belt dimensions. V-belts, ratio of tensions, belt size and number of belts."] },
      { "name": "Unit-II", "topics": ["Gears: Introduction of gear drives, different types of gears, Materials used for gears. Standards for gears and specifications. Spur Gear Design: Basic analysis of gear tooth-Bending stress-Lewis equation, refined analysis of gear tooth -bending strength-procedure, gear tooth surface fatigue analysis-procedure, spur gear design procedures, Design of Helical, Bevel and Worm gears. Concepts of Design for manufacturability."] },
      { "name": "Unit-III", "topics": ["Bearings: Introduction. Materials used for Bearings. Classification of bearings and mounting of bearings.", "Design of sliding contact bearings: Properties and types of Lubricants, Design of Hydrostatic and Hydro dynamic sliding contact bearings. Design of Rolling Contact Bearings: Different types of rolling element bearings and their constructional details, static load carrying capacity. Dynamic load carrying capacity. Load-life relationship, selection of bearing life. Design for cyclic loads and speeds. Selection of Ball and Roller bearings."] },
      { "name": "Unit-IV", "topics": ["Analysis of Column And Struts : Column and strut, Types of columns, end conditions, Euler’s column Theory, different cases in Euler’s Theory, Limitations of Euler’s Theory, Rankine's formula.", "I.C. Engine parts: Introduction. Materials used. Connecting rod for I.C. Engines, Loads on connecting rod, cross-sections, materials, Design of connecting rod. Design of piston."] },
      { "name": "Unit-V", "topics": ["Fly wheels: Introduction, Design of solid disk type and rimmed fly wheels.", "Design of Brakes: Block brake with short shoe & long shoe, Pivoted block brake with long shoe, band brakes, internal expanding shoe, and thermal considerations.", "Clutches: Single and multiple disc clutches, cone clutch, friction materials."] }
    ]
  },
  {
    "code": "PC3104ME",
    "title": "Production Planning and Control",
    "units": [
      { "name": "Unit I", "topics": ["Introduction:", "Definition – Objectives of production Planning and Control – Functions of production planning and control – Elements of production control – Types of production – Organization of production planning and control department – Internal organization of department. Forecasting: Importance of forecasting –Types of forecasting, their uses –General principles of Forecasting –Forecasting techniques- qualitative methods- Jury/Expert Method , Survey of Expert opinion method , Sales force composite method, Survey of buyers intention method and quantitative methods-Simple average, moving average, smoothing coefficient, Least Square method."] },
      { "name": "Unit II", "topics": ["Inventory Management: Functions of inventories – relevant inventory costs – ABC analysis – VED analysis – EOQ model – Inventory control systems – P-Systems and Q-Systems Introduction to MRP-I, MRP-II & ERP, JIT inventory, Kanban system"] },
      { "name": "Unit III", "topics": ["Routing & Scheduling: Definition of Routing – Routing procedure –Route sheets – Bill of material – Factors affecting routing procedure. Definition of Scheduling – Activities-Difference with loading, Scheduling types: Forward, Backward scheduling, Job shop scheduling methods – Arrival pattern, processing pattern, number of workers available, machine varieties available, Priority rules for job sequencing FIFO, SPT,SOT, EDD, STR, CR, LISO, Random Orders. Scheduling Techniques Gantt Charts, LOB, Johnson’s job sequencing rules- n jobs on 2machines, n jobs on 3 machines, n jobs on m machines."] },
      { "name": "Unit IV", "topics": ["Line Balancing and Aggregate Planning:", "Introduction to line balancing, objectives, terms related to line balancing, procedures, simple problems; Introduction to Aggregate Planning, Inputs to aggregate planning, strategies- Line strategy, chase strategy, capacity options, demand options."] },
      { "name": "Unit V", "topics": ["Dispatching: Centralized and Decentralized Dispatching- Activities of dispatcher – Dispatching procedure – follow-up – definition – Reason for existence of functions – types of follow up, applications of computer in production planning and control."] }
    ]
  },
  {
    "code": "PE-I",
    "title": "Professional Elective - I",
    "isGroup": true,
    "variants": [
      {
        "code": "PE3105ME",
        "title": "Design of Thermal Systems",
        "units": [
          { "name": "Unit-I", "topics": ["Solar radiation: Properties of sunlight. Sun-Earth Relationships, Absorption by the atmosphere. Peak sun hours, the declination of the Sun, Determination of Solar time, solar angle, solar window. solar radiation is measuring devices: Pyrheliometers, Pyranometers. Pyrgeometer, Net radiometer, Sunshine recorder, Estimation of Average Solar radiation. Solar irradiance at surfaces"] },
          { "name": "Unit-II", "topics": ["Solar cells and modules: The function of solar cells from semiconductor physics. Different solar cell technologies and fabrication methods. Concepts for increasing efficiency based on loss analysis. Wavelength sensitivity. Series connection and parallel connection of solar cells to modules. Module function and characteristics. Shading of cells and modules."] },
          { "name": "Unit-III", "topics": ["Solar cell systems: System components and their functions. Calculating output and dimensioning of solar cell systems. Concentrated sunlight and solar power (CSP).Properties of optical concentration systems. Solar thermal products. Concepts for increasing efficiency based on loss analysis. in a CSP system and their functions. Design of Photovoltaic Systems"] },
          { "name": "Unit-IV", "topics": ["Solar thermal: Thermodynamic description of solar collectors. Optical properties of solar collectors and technologies for fabrication. Solar thermal systems for different applications: Solar Water Heating (Active and Passive), Solar Industrial Process Heat, Solar Thermal Power Systems in India and abroad. Storage of solar generated heat. Design of Active Systems by Utilizability Methods, Design of Passive and Hybrid Heating Systems."] },
          { "name": "Unit-V", "topics": ["Performance Testing of Solar Collectors:", "Governing equations for evaluation of performance. Methods of testing, testing procedures, testing of liquid and air flat plate collectors. Cylindrical, parabolic concentrators. Overall performance of heating panels. Selection of materials - Absorbing heat transfer fluids.", "Hybrid systems: Combinations of solar thermal and solar cell systems. Overview of different applications."] }
        ]
      },
      {
        "code": "PE3106ME",
        "title": "Non-conventional Energy Sources",
        "units": [
          { "name": "UNIT-I", "topics": ["Introduction: Distinction between Conventional and Non-conventional sources of energy- Brief description of the different sources.", "Wind Energy: Brief History of wind power-Principles of wind power-Operation of a wind turbine-Site Characteristics."] },
          { "name": "UNIT-II", "topics": ["Solar Energy: Solar energy option-Solar radiation-Solar flat Plate Collectors-Air heaters- Collectors with booster mirrors-Concentric collectors-Thermal storage systems. Solar Photovoltaic (SPV) Systems: Introduction. Prospects of SPV systems. Principle of a PV cell. Large scale SPV systems. Economic considerations of SPV Systems. PV Cell Technology. Merits and limitations of SPV Systems. Applications of SPV Systems-street lighting, domestic lighting, Battery charging, SPV pumping systems. Concept of Satellite solar power systems (SSPS)."] },
          { "name": "UNIT-III", "topics": ["Geothermal Energy: Origin and Types of geothermal energy-Operational difficulties-Vapor dominated systems-Liquid dominated systems-Petro-thermal systems-Hybrid geothermal systems.", "Magneto Hydro Dynamic (MHD) Power Generation: MHD systems-Open and closed systems-MHD design problems and Developments-Advantages of MHD Systems."] },
          { "name": "UNIT-IV", "topics": ["Energy from Oceans: Ocean temperature differences-the open and closed cycle analysis- Modification of the Open cycle Analysis-closed or the Anderson cycle Analysis-Ocean Waves-Wave motions and tides-Energy from the Waves."] },
          { "name": "UNIT-V", "topics": ["Bio Energy: Introduction-Biomass conversion-Technologies-Wet processes-Dry processes- Photosynthesis-Biogas generation-Biogas from plant wastes-methods of maintaining Biogas production-Utilization of biogas. Biomass gasification- Applications of gassifiers."] }
        ]
      },
      {
        "code": "PE3107ME",
        "title": "Power Plant Engineering",
        "units": [
          { "name": "UNIT – I:", "topics": ["Introduction to the Sources of Energy – Resources and Development of Power in India. Steam Power Plant: Plant Layout, Working of different Circuits, Fuel and handling equipments, types of coals, coal handling, choice of handling equipment, coal storage, Ash handling systems. Combustion Process: Properties of coal – overfeed and underfeed fuel beds, traveling grate stokers, spreader stokers, retort stokers, pulverized fuel burning system and its components, combustion needs and draught system, cyclone furnace, design and construction, Dust collectors, cooling towers and heat rejection. Corrosion and feed water treatment."] },
          { "name": "UNIT – II:", "topics": ["Internal Combustion Engine Plant: Diesel Power Plant: Introduction – IC Engines, types, construction– Plant layout with auxiliaries – fuel supply system, air starting equipment, lubrication and cooling system – super charging. Gas Turbine Plant: Introduction – classification – construction – Layout with auxiliaries – Principles of working of closed and open cycle gas turbines. Combined Cycle Power Plants and comparison. Direct Energy Conversion: Solar energy, Fuel cells, Thermo electric and Thermo ionic, MHD generation."] },
          { "name": "UNIT – III:", "topics": ["Hydro Electric Power Plant: Water power – Hydrological cycle / flow measurement – drainage area characteristics – Hydrographs – storage and Pondage – classification of dams and spill ways. Hydro Projects And Plant: Classification – Typical layouts – plant auxiliaries – plant operation pumped storage plants. Power From Non-Conventional Sources: Utilization of Solar- Collectors- Principle of Working, Wind Energy – types – HAWT, VAWT -Tidal Energy."] },
          { "name": "UNIT – IV:", "topics": ["Nuclear Power Station: Nuclear fuel – breeding and fertile materials – Nuclear reactor – reactor operation. Types of Reactors: Pressurized water reactor, Boiling water reactor, sodium-graphite reactor, fast Breeder Reactor, Homogeneous Reactor, Gas cooled Reactor, Radiation hazards and shielding – radioactive waste disposal."] },
          { "name": "UNIT – V:", "topics": ["Power Plant Economics and Environmental Considerations: Capital cost, investment of fixed charges, operating costs, general arrangement of power distribution, Load curves, load duration curve. Definitions of connected load, Maximum demand, demand factor, average load, load factor, diversity factor – related exercises. Effluents from power plants and Impact on environment – pollutants and pollution standards – Methods of Pollution control."] }
        ]
      }
    ]
  },
  {
    "code": "HS3108ELW",
    "title": "Law and Engineering",
    "units": [
      { "name": "Unit-I", "topics": ["The Legal System - Meaning, nature and definition of jurisprudence -Schools of jurisprudence- Analytical, Historical, Philosophical and Sociological Schools of jurisprudence - Meaning and Definition of Law - The Nature and functions of Law - Sources of Law - Sources of Law - Legal and Historical sources —Precedent/Case Law as Source of Law - Definition of Precedent, Kinds of Precedent - Legislation as Source of Law- Definition of Legislation -Classification of Legislation – Supreme and Subordinate Legislation – Court System and Hierarchy of Judiciary in India - Concept of Alternative Dispute Resolution System (ADR) – History and Reasons for the growth of ADR –Important forms of ADR – Mediation - Negotiation - Arbitration - Definition of Arbitration and Essentials - Online Dispute Resolution (ODR)."] },
      { "name": "Unit-II", "topics": ["Society and Constitutional law - Social Change: Definition, nature and characteristics of Social change – Social Transformation - Factors of Social Change - Law and social Change - State, Law and Society, their interrelationship and interdependence - Identification of Goals of Social Changes in Indian Constitution - Constitution-Meaning and Significance - Nature and Salient Features of Indian Constitution – Preamble to Indian Constitution –Fundamental Rights - Right to Equality(Art.14-18) – Freedoms and Restrictions under Art.19 - Right to Life and Personal Liberty - Directive Principles of State Policy – Significance – Nature –Classification."] },
      { "name": "Unit-III", "topics": ["Contract law - Definition and essentials of a Valid Contract – Meaning and Definition of Consideration - Capacity of the parties to enter into contract -Concepts of Free Consent - Lawful Object - Illegal agreements - Void and Voidable contracts - Discharge of Contracts - Remedies for breach of contract -Kinds of damages - Contract of sale of Goods – Formation of contract of sale -Sale and Agreement to Sell -Conditions and Warranties - Express and implied Conditions and Warranties - Caveat Emptor - Rights and duties of seller and buyer before and after sale - Rights of Unpaid Seller - Remedies of breach."] },
      { "name": "Unit-IV", "topics": ["Business Organizations - Corporate Personality - General Principles of Company Law – Companies Act, 2013 - Nature and Definition of Company -Characteristics of a Company - Different kinds of Company - Private Company and Public Company – Registration & Incorporation of Company -Advantages and Disadvantages of Incorporation - Lifting of the Corporate Veil – Company distinguished from Partnership and Limited Liability Partnership - Shares &Stock - Kinds of shares - Share Capital - Directors – Different kinds of Directors -Appointment, position , qualifications and disqualifications - Powers of Directors - Rights and Duties of Directors – Corporate Governance and Role of Directors – Meetings of Company - Winding up of Companies- Modes of Winding up of Companies."] },
      { "name": "Unit-V", "topics": ["Meaning, Definition and Concept of Environment - Types of Environment - Concept of Pollution – Sources of Pollution, Types of Pollution, and Effects of Pollution – Ozone Depletion – Global Warming – Climate Change -The Environment Protection Act of 1986 - Main Aims and Objectives of the Act -Meaning, Nature, Classification and significance of Intellectual Property – The main forms of Intellectual Property - Patents - Concept of Patent - Kinds of Patents - The Patents Act, 1970 - Rights and obligations of a patentee - The notion of ‘abuse’ of patent rights - Infringement of patent rights and remedies available - Meaning, Definition and Nature of Cyber crimes - Information Technology Act, 2000 - Specific Cyber crimes - Cyber Stalking – Hacking – Child Pornography - Phishing – Cyber Crimes and Issues of Privacy - Investigation and Jurisdiction over Cyber crimes."] }
    ]
  }
];
