export const semester4 = [
  {
    "code": "HS 301MC",
    "title": "Managerial Economics and Accountancy",
    "units": [
      { "name": "Unit – I", "topics": ["Meaning and Nature of Managerial Economics: Managerial Economics and its usefulness to Engineers, Fundamental Concepts of Managerial Economics-Scarcity, Marginalism, Equimarginalism, Opportunity costs, Discounting, Time Perspective, Risk and Uncertainty, Profits, Case study method."] },
      { "name": "Unit – II", "topics": ["Consumer Behavior: Law of Demand, Determinants, Types of Demand; Elasticity of Demand (Price, Income and Cross-Elasticity); Demand Forecasting, Law of Supply and Concept of Equilibrium. (Theory questions and small numerical problem can be asked)"] },
      { "name": "Unit – III", "topics": ["Theory of Production and Markets: Production Function, Law of Variable Proportion, ISO quants, Economics of Scale, Cost of Production (Types and their measurement), Concept of Opportunity Cost, Concept of Revenue, Cost-Output relationship, Break-Even Analysis, Price - Output determination under Perfect Competition and Monopoly (theory and problems can be asked)"] },
      { "name": "Unit – IV", "topics": ["Capital Management: Significance, determination and estimation of fixed and working capital requirements, sources of capital, Introduction to capital budgeting, methods of payback and discounted cash flow methods with problems. (Theory questions and numerical problems on estimating working capital requirements and evaluation of capital budgeting opportunities can be asked)"] },
      { "name": "Unit – V", "topics": ["Book-keeping: Principles and significance of double entry book keeping, Journal, Subsidiary books, Ledger accounts, Trial Balance, concept and preparation of Final Accounts with simple adjustments, Analysis and interpretation of Financial Statements through Ratios. (Theory questions and numerical problems on preparation of final accounts, cash book, petty cash book, bank reconciliation statement, calculation of some ratios)"] }
    ]
  },
  {
    "code": "PC 401CE",
    "title": "Mechanics of Materials",
    "units": [
      { "name": "Unit – I", "topics": ["Deflection: Slope and deflection by double integration method for cantilever, simply supported beams and overhanging beams carrying one, two point loads, u.d.l. and uniformly varying load over entire span. Moment area and conjugate beam method", "Propped cantilevers: Cantilever beams on elastic and rigid props for point loads and UDL only. Calculation of reactions, B.M. and S.F. diagrams, and deflections.", "Fixed Beams: Determination of shear force, bending moment slope and deflection in fixed beams with and without sinking of supports for (i) point loads (ii) u.d.l. (iii)uniformly varying load over entire span. Moment area and conjugate beam method", "Continuous Beams: Determination of moments in continuous beams with and without sinking of supports by theorem of three moments, S.F. and B.M. diagrams."] },
      { "name": "Unit – II", "topics": ["Column analogy method: Application to fixed beams- analogous column- stiffness and carryover factors", "Strain energy: Strain energy and resilience in statically determinate bars subjected to gradually applied, suddenly applied, impact and shock loads. Resilience of beams. Deflections from resilience. Castigliano Theorem - I and its application to beams. Reciprocal theorem. Static indeterminacy and kinematic indeterminacy of structures."] },
      { "name": "Unit – III", "topics": ["Strain energy method: Deflections of statically determinate trusses and frames using unit load method.", "Redundant trusses and frames: Analysis of plane trusses with one degree of redundancy (internal /external) and plane frames with one degree of redundancy, Lack of fit and temperature effect."] },
      { "name": "Unit – IV", "topics": ["Torsion and Springs- Derivation of torsion equation and its assumptions. Applications of the equation of the hollow and solid circular shafts, torsional rigidity, Combined bending and torsion of circular shafts, principal stress and maximum shear stresses under combined loading of bending and torsion. Analysis of close-coiled-helical springs.", "Columns and Struts- Euler’s theory for long columns- different end conditions- equivalent length- Rankine’s theory. Eccentrically loaded columns- Secant and Perry's formulae."] },
      { "name": "Unit – V", "topics": ["Unsymmetrical bending of beams: Location of neural axis, maximum stresses for rectangular section .Symmetric channel section.", "Shear Centre: Shear stress, shear flow, locating shear center for angle section channel section and T- section, with one axis of symmetry."] }
    ]
  },
  {
    "code": "PC 402CE",
    "title": "Structural Engineering",
    "units": [
      { "name": "Unit – I", "topics": ["Materials and Structural Design Criteria Development of design philosophies-Working stress method, Ultimate load method, and Limit state method - Concepts, Characteristics loads and strengths, Partial safety factors, Stress-strain relationship for concrete and steel, stress block parameters.", "Working stress method: Design of RCC beams - Balanced, under-reinforced and over reinforced sections - Rectangular, T and L sections, Design of singly and. doubly reinforced rectangular, T and L sections."] },
      { "name": "Unit – II", "topics": ["Introduction to the analysis and design", "Limit state of collapse in flexure: Assumptions, Design for flexure - Singly and doubly reinforced rectangular, T and L sections.", "Limit state of collapse in shear and torsion: Design for shear and torsion. Limit states of serviceability: Check for deflection and cracking."] },
      { "name": "Unit – III", "topics": ["Design of Structural Elements", "Design of slabs (Limit state method): Design of one way and two way slabs - Simply supported and continuous slabs subjected to uniformly distributed loads, Detailing of reinforcement, Check for serviceability of slabs.", "Design of stair cases (Limit state method): Types of stairs, Effective span, Distribution of loading on stairs, Design and detailing of dog-legged stair cases."] },
      { "name": "Unit – IV", "topics": ["Design of columns (Limit state method): Assumptions, Design of axially loaded circular, square and rectangular columns, Design of columns with uni-axial and bi-axial bending interaction diagrams", "Design of footings (Limit state method): Design of isolated footings of uniform depth and sloped footings, Deign of square, rectangular and circular footings as per IS code, Design of combined rectangular slab footing, Combined rectangular beam and slab footing for two columns"] },
      { "name": "Unit – V", "topics": ["System Design Concepts; Special Topics that may be Covered as Part of the Design Project Discussions; Introduction - Types of bridges, materials of construction, codes of practice (Railway and Highway bridges), aesthetics, loading standards (IRC, RDSO, AASHTO), Concrete Bridges - Materials and infrastructure requirements, precast systems and materials used for precast and cast in-situ bridges. Bridge deck and approach slabs, design of bridge deck systems, slab-beam systems design philosophies."] }
    ]
  },
  {
    "code": "PC 403CE",
    "title": "Hydraulic Engineering",
    "units": [
      { "name": "Unit – I", "topics": ["Steady uniform flow through open channels: Descriptions and definitions, difference between pipe flow and channel flow, velocity and pressure distributions in a channel cross-section, energy and momentum correction coefficients, friction to flow in open channels, uniform flow, Manning and Chezy formulae, most efficient channel sections, specific energy, concept and applications of critical depth. Gradually varied flow: Significance of Froude number, dynamic equation of gradually varied flow, classification of gradually varied flow profiles"] },
      { "name": "Unit – II", "topics": ["Boundary layer: Definition, laminar and turbulent boundary layers, boundary layer thickness, displacement thickness, momentum thickness, and energy thickness, hydro-dynamically smooth and rough boundaries, and boundary layer separation.", "Drag and Lift: fundamental concepts of drag and lift forces, drag on a sphere, cylinder, flat plate, and aerofoil."] },
      { "name": "Unit – III", "topics": ["Dimension analysis and model studies: Dimensional analysis and a tool in experimental hydraulics, Buckingham’s Pie theorem, applications, geometric, kinematic and dynamic similarity, similarity laws, significance of Reynolds, Froude and Mach similarity laws, different types of models and their scale ratios."] },
      { "name": "Unit – IV", "topics": ["Hydraulic turbines: Classification, specific speed, velocity triangles, power developed, efficiencies, principles of design of impulse and reaction turbines, turbine laws and constants, characteristic curves, selection of turbines."] },
      { "name": "Unit – V", "topics": ["Centrifugal pumps: Components, work done and efficiency, minimum starting speed, Euler head equation, specific speed and characteristic curves of centrifugal pump, pumps in series and parallel."] }
    ]
  },
  {
    "code": "PC 404CE",
    "title": "Hydrology and Water Management",
    "units": [
      { "name": "Unit – I", "topics": ["General: Definition, relation to engineering design, hydrological cycle, importance of hydrology and its application in engineering.", "Rainfall: Definition, types of rainfall, measurement of rain fall, types of raingauges, network of stream gauging, definition, types of rainfall, measurement of rain fall, types of raingauges, network of stream gauging, presentation of precipitation data, mean aerial rainfall; thiessen polygon, isohyetal methods., depth- area- duration curve, dependable rainfall.", "Infiltration: Evaporation, transpiration-definitions and processes."] },
      { "name": "Unit – II", "topics": ["Runoff: Definition, runoff process, factors affecting runoff, determination of runoff, importance of stream gauging, runoff formulae and runoff tables, dependable yield of a basin.", "Floods: Definition, causes, importance of flood studies, flood peak and flood hydrograph, methods of computing flood peak, empirical methods, rational formula, unit hydrograph method, flood frequency studies, Weibul’s and Gumble’s extreme value methods."] },
      { "name": "Unit – III", "topics": ["Ground water: Types of aquifers, aquifer parameters, specific yield, storage coefficient, coefficients of permeability and transmissivity, Darcy’s law, types of well, steady radial flow to wells in confined and unconfined aquifers, yield of open wells, safe yield, constant level pumping test and recuperation test."] },
      { "name": "Unit – IV", "topics": ["Statistics in Hydrology: Introduction, Statistical parameters; central tendency parameters, dispersion characteristics, skewness, probability distribution; discrete and continuous distribution., frequency analysis; log pearson type III distribution., regression and correlation; standard forms of bivariate equations., multivariate linear regression and correlation., analysis of time series., selection of a design return period, determination of permissible risk."] },
      { "name": "Unit – V", "topics": ["Irrigation: Definition, necessity of irrigation, types of irrigation, advantages and ill-effects of irrigation.", "Soil-water-plant relationship: Vertical distribution of soil moisture, soil moisture tension, soil moisture stress, soil moisture constants, plant water relationship, moisture stress and plant response, consumptive use, crop factor, duty, factors affecting duty, types of crops and their water requirements, crop rotation."] }
    ]
  },
  {
    "code": "PC 405CE",
    "title": "Construction Engineering and Management",
    "units": [
      { "name": "Unit – I", "topics": ["Basics of Construction- Unique features of construction, Construction project planning- Stages of project planning, Sequence of events in general Civil Engineering construction projects, Construction Schedule, work break-down structure. Development of management techniques, Bar charts, Gantt charts, CPM and Network analysis examples."] },
      { "name": "Unit – II", "topics": ["PERT techniques, Introduction to cost analysis, Cost reduction in construction management. Cost time analysis, Crashing the Network, Resource Leveling and smoothing."] },
      { "name": "Unit – III", "topics": ["Development of Operations Research (OR), Quantitative Analysis and Decision Making, need for linear programming, standard form of Linear programming, Graphical Method. An algebraic overview of Simplex Method, solving minimization and maximization problems, Dual method, case studies."] },
      { "name": "Unit – IV", "topics": ["Safety Engineering, Safety program, Direct and Indirect loss due to accident, Classification of Construction accidents and causes, Location hazards and their elimination, Safety in demolition of buildings, Safety in storage and handling of materials and equipments"] },
      { "name": "Unit – V", "topics": ["Contracts Management – Basics, Importance of contracts; Types of Contracts, parties to a contract; Construction Equipment basics: Conventional construction methods Vs Mechanized methods and advantages of latter; Equipment for Earthmoving, Dewatering; Concrete mixing, transporting & placing; Cranes, Hoists and other equipment for lifting; Equipment for transportation of materials."] }
    ]
  },
  {
    "code": "PC 401BS",
    "title": "Engineering Geology",
    "units": [
      { "name": "Unit – I", "topics": ["Rocks: Distinguishing features of igneous, sedimentary and metamorphic rocks Geological description and Indian occurrence of Granite, Basalt, Dolerite, Gabbro, Laterite, Sandstone Shale, Limestone Slate, Gneiss, Quartzite, Marble, Khondalite and charnockite.", "Geological Structures: Folds, Fractures joints and faults - Fundamental types, mechanism origin and classifications of structures; Field identification and Engineering analysis of structures"] },
      { "name": "Unit – II", "topics": ["Rock Weathering: Processes and end - products of weathering; susceptibility of rocks to weathering, Assessment of the degree of weathering and its classification.", "Geology of Soils: Formation, geological classification, description and Engineering use of soils Types of Indian soils.", "Hydrogeology: Hydrologic cycle, water table, aquifers, occurrence of ground water in various lithological formations, ground water movement, springs, ground water exploration and ground water provinces of India."] },
      { "name": "Unit – III", "topics": ["Geomorphology: Evolution, characteristics features and Engineering, considerations of fluviatile, Aeolian, glacial and marine land forms.", "Rock Mechanics: Engineering properties- of rocks Stress - Strain behaviour of rocks under uniaxial compression.", "Site Investigation: Aerial Photographs, Electrical: Resistivity and Seismic refraction methods."] },
      { "name": "Unit – IV", "topics": ["Rock as a Construction Material: Geological considerations III the selection of Concrete aggregate, Highway and Runway aggregates, building stones, Decorative stones, Roofing and facing stones. Building stones of India.", "Geology of Dams and Reservoirs: Types of Dams, Problems associated with Dam foundations and reservoirs, Engineering Geological investigations for a masonry dam site, Analysis of dam failure; Engineering Geology of major Dam sites of India."] },
      { "name": "Unit – V", "topics": ["Tunnels: Stand - up time of different rocks, Engineering Geological investigations of tunnels in rock, problems in tunneling, pay line and over break, logging of tunnels and geology of some well known Indian tunnels.", "Geological Hazards: Geological aspects of Earthquakes, Tsunamis and Landslides; Disaster prevention, mitigation and management."] }
    ]
  }
];
