export const semester5 = [
  {
    "code": "HS 3101LA",
    "title": "Professional Practice Building Laws & Ethics",
    "units": [
      { "name": "Unit – 1 : Practices of Building Bye –laws – I", "topics": ["Definitions - General Definitions - Jurisdiction and Applicability of the building bye laws And building documentation procedures - Development and part construction In case of Part construction and Change of use / occupancy - Reconstruction Existing approved general building. Guidelines and byelaws for obtaining permissions for Residential and Commercial spaces"] },
      { "name": "Unit – 2 : Practices of Building Bye - laws – II", "topics": ["General building requirements and services - Requirements of spaces for various areas in the residential buildings, Special requirements for low income houses, Other requirements including Fire, Open spaces, height limitations, Lighting and Ventilation. Building Services like plumbing, sanitation etc. Model Building Bye-laws (latest)"] },
      { "name": "Unit – 3: Infrastructure and Real Estate Engineering byelaws", "topics": ["Real Estate Scope - classification of real estate activities and peculiarities; Factors affecting real estate market; Role of Government in real estate market; Statutory provisions, Laws, rules, and regulation, land use controls in property development, registration And licensing requirements –Real estate development - Functions of real development like project formulation, feasibility studies, developing, costing and financing, managing including planning, Scheduling and monitoring of real estate projects,"] },
      { "name": "Unit - 4: Contact law and conflict issues", "topics": ["Contracts and management of Contracts - Types of engineering contracts- procurement philosophy - Definition and essentials of a Contract - Clauses for contracts – Types of engineering contracts and its formulation -Preparation of tender documents – Issues related to tendering process – Awarding Contract - Provisions of Contract law, Indian Contract Act,1872 Laws related to construction industry - Labour and Industrial laws – Payment of Wages Act- Contract labour Workmen’s Compensation Act – Insurance and Industrial dispute Act."] },
      { "name": "Unit – 5 : Disputes and their resolutions Mechanisms", "topics": ["Concept of ADR– Negotiation – Mediation - Conciliation - Arbitration –Ombudsman – Arbitration Agreement - Essentials - Rule of severability - Interim measures ordered by arbitral tribunal. Conduct of Arbitral Proceedings. Making of Arbitral Award and termination of proceedings - Rules applicable to substance of dispute — Settlement - Form and contents of arbitral award - Termination proceeding."] }
    ]
  },
  {
    "code": "HS3102 LA",
    "title": "Law and Engineering",
    "units": [
      { "name": "Unit-I: The Legal System", "topics": ["Meaning, nature and definition of jurisprudence - Schools of jurisprudence- Analytical, Historical, Philosophical and Sociological Schools of jurisprudence - Meaning and Definition of Law - The Nature and functions of Law - Sources of Law - Legal and Historical sources — Precedent/Case Law as Source of Law - Definition of Precedent, Kinds of Precedent - Legislation as Source of Law- Definition of Legislation - Classification of Legislation – Supreme and Subordinate Legislation – Court System and Hierarchy of Judiciary in India - Concept of Alternative Dispute Resolution System (ADR) – History and Reasons for the growth of ADR –Important forms of ADR – Mediation - Negotiation - Arbitration - Definition of Arbitration and Essentials - Online Dispute Resolution (ODR)."] },
      { "name": "Unit-II: Society and Constitutional law", "topics": ["Social Change: Definition, nature and characteristics of Social change – Social Transformation - Factors of Social Change - Law and social Change - State, Law and Society, their inter-relationship and interdependence - Identification of Goals of Social Changes in Indian Constitution - Constitution-Meaning and Significance - Nature and Salient Features of Indian Constitution – Preamble to Indian Constitution – Fundamental Rights - Right to Equality(Art.14-18) – Freedoms and Restrictions under Art.19 - Right to Life and Personal Liberty - Directive Principles of State Policy – Significance – Nature – Classification."] },
      { "name": "Unit-III: Contract law", "topics": ["Definition and essentials of a Valid Contract - Meaning and Definition of Consideration - Capacity of the parties to enter into contract - Concepts of Free Consent - Lawful Object - Illegal agreements - Void and Voidable contracts - Discharge of Contracts - Remedies for breach of contract - Kinds of damages - Contract of sale of Goods – Formation of contract of sale - Sale and Agreement to Sell -Conditions and Warranties - Express and implied Conditions and Warranties - Caveat Emptor - Rights and duties of seller and buyer before and after sale – Rights of Unpaid Seller - Remedies of breach."] },
      { "name": "Unit-IV: Business Organizations", "topics": ["Corporate Personality - General Principles of Company Law – Companies Act, 2013 - Nature and Definition of Company - Characteristics of a Company - Different kinds of Company - Private Company and Public Company – Registration & Incorporation of Company –Advantages and Disadvantages of Incorporation - Lifting of the Corporate Veil – Company distinguished from Partnership and Limited Liability Partnership - Shares & Stock - Kinds of shares - Share Capital - Directors – Different kinds of Directors - Appointment, position , qualifications and disqualifications - Powers of Directors - Rights and Duties of Directors – Corporate Governance and Role of Directors – Meetings of Company - Winding up of Companies-Modes of Winding up of Companies."] },
      { "name": "Unit-V: Meaning, Definition and Concept of Environment", "topics": ["Types of Environment - Concept of Pollution – Sources of Pollution, Types of Pollution, and Effects of Pollution – Ozone Depletion – Global Warming – Climate Change - The Environment Protection Act of 1986 - Main Aims and Objectives of the Act - Meaning, Nature, Classification and significance of Intellectual Property – The main forms of Intellectual Property - Patents - Concept of Patent - Kinds of Patents - The Patents Act, 1970 - Rights and obligations of a patentee - The notion of ‘abuse’ of patent rights - Infringement of patent rights and remedies available - Meaning, Definition and Nature of Cyber crimes - Information Technology Act, 2000 - Specific Cyber crimes - Cyber Stalking – Hacking – Child Pornography - Phishing – Cyber Crimes and Issues of Privacy - Investigation and Jurisdiction over Cyber crimes."] }
    ]
  },
  {
    "code": "PC 3103 CE",
    "title": "Soil Mechanics",
    "units": [
      { "name": "UNIT–I: Introduction", "topics": ["History of soil mechanics- Importance of soil engineering- important soil deposits of India. Three phase soil system, volumetric relationships and weight-volume relationships. Determination of Index Properties: Water content, Specific gravity, Grain size distribution by sieve and hydrometer analysis, Relative density, Atterberg limits and indices."] },
      { "name": "UNIT- II: Soil Classification", "topics": ["Classification of soil systems – Particle size classification, Textural classification, AASHTO classification, Unified soil classification and Indian soil classification- Field identification of soils.", "Soil Water: Capillarity in soils, Permeability of soils, Darcy’s law, Determination of permeability of soils, Permeability of stratified soils, Field permeability determination, Seepage velocity, Absolute coefficient of permeability, Factors affecting permeability- Effective stress principle- Effective stress under different field conditions. Seepage pressure-Quick sand condition"] },
      { "name": "UNIT - III: Compaction Process", "topics": ["Compaction Mechanism; factors affecting compaction. Laboratory determination of compaction characteristics - standard and modified Proctor tests - IS Light and Heavy compaction tests; Field surface compaction: compaction equipment, procedure, quality control.", "Consolidation Process: Spring analogy - Void ratio and effective stress (e Vs log p) relationship - Terzaghi's theory of one dimensional consolidation - Assumptions and derivation of GDE - Computation of magnitude of settlement (using Cc, mv ) and rate of settlement (cv , Tv, d)."] },
      { "name": "UNIT - IV : Shear Strength", "topics": ["Significance of Shear strength in soils - Mohr - Coulomb equation - shear parameters - Laboratory tests for determination of shear strength - Direct shear test, Tri-axial compression test, Un-confined compression test, Vane shear test, Factors affecting shear strength of cohesion-less and cohesive soils."] },
      { "name": "UNIT - V : Earth Pressure", "topics": ["States of earth pressure - Active, passive, at rest condition; Rankine's theory: computation of active and passive earth pressure in c-less and cohesive soils; Coulomb’s Wedge theory: Rehbhan's graphical solution: stability of earth retaining gravity wall.", "Slope stability: Definition and classification of slopes -types of slope failure - Factors of safety with respect to cohesion, angle of shearing resistance, Height - Analysis of stability of slope using Swedish slip circle method and Taylor's stability number."] }
    ]
  },
  {
    "code": "PC 3104 CE",
    "title": "Water Resource Engineering",
    "units": [
      { "name": "UNIT - I", "topics": ["Water Resources Projects: Single and multipurpose projects, general principles of irrigation water rates, components of water allocation systems, riparian rights, groundwater rights, environmental and water quality management aspects of reservoir system operations.", "Storage works: Purpose, selection of site, zones of storage, computation of storage capacity, fixation of different levels of reservoirs (LWL, FRL, MWL), evaporation reduction techniques."] },
      { "name": "UNIT - II", "topics": ["Dams: Classification of dams, selection of site for a dam, physical factors governing the selection of types of a dam.", "Gravity dams : Forces acting on a gravity dam, modes of failure and criteria for structural stability of gravity dams, principal and shear stresses, gravity method of stability analysis, elementary and practical profiles of a gravity dam, high and low gravity dams, functions, and types of galleries in gravity dams, foundation treatment for gravity dams."] },
      { "name": "UNIT - III", "topics": ["Earth dams: Types of earth dams, causes of failure of earth dams, criteria for the safe design of an earth dam, computation of seepage from flow net, phreatic line in an earth dam (for homogeneous sections with and without filter cases), design of earth dams to suit available materials, embankment and foundation seepage control measures."] },
      { "name": "UNIT - IV", "topics": ["Tank irrigation: Types, site selection, causes for the failure of tank weirs, design of tank weirs, and general specifications for the construction of tank weirs.", "Spillways: Different types of spillways, energy dissipation below spillways, different types of spillway crest gates, stilling basin appurtenances (descriptive details only)."] },
      { "name": "UNIT - V", "topics": ["Hydropower structures - Storage power plant, Runoff River plant, Pumped storage plant, Water conveyance systems, Tunnels and Penstocks, Gates, Surge tanks, Power house layout"] }
    ]
  },
  {
    "code": "PC 3105 CE",
    "title": "Theory of Structures",
    "units": [
      { "name": "UNIT - I", "topics": ["Slope deflection method: Analysis and Application of the method to continuous beams with and without sinking of supports, single bay - portal frames (Degree of freedom not exceeding three)"] },
      { "name": "UNIT - II", "topics": ["Moment distribution method: Application of the method to continuous beams with and without sinking of supports, portal frames (static indeterminacy not exceeding three)"] },
      { "name": "UNIT - III", "topics": ["Kani's Method: Application of the method to continuous beams with and without support sinking, portal frames (static indeterminacy not exceeding three)"] },
      { "name": "UNIT - IV", "topics": ["Approximate method of Analysis.", "Multi-storeyed building frames: Analysis and design for vertical loads by substitute frame method - Analysis and design of Portal frames by portal method, cantilever method and factor method."] },
      { "name": "UNIT - V", "topics": ["Elastic theory of arches: Eddy's theorem, three hinged parabolic and segmental arches, determination of horizontal thrust, bending moment, normal thrust and radial shear for static loading, influence lines for horizontal thrust, bending moment, normal thrust and radial shear.", "Two hinged arches: parabolic and segmental, determination of horizontal thrust, bending moment, normal thrust and radial shear for static loading."] }
    ]
  },
  {
    "code": "PC 3106 CE",
    "title": "Concrete Technology",
    "units": [
      { "name": "UNIT-I", "topics": ["Constituents of Concrete:", "Cement: Types of cements and their composition- manufacture of portland cement -hydration of cement and hydration product, Structure of hydrated cement- heat of hydration, Gel theories, Tests on physical properties of cements.", "Aggregate: Classification of aggregates, particle shape and texture, bond strength of aggregates and its influence on strength of concrete, porosity, absorption and moisture content and their influence, soundness of aggregate, alkali aggregate reaction, sieve analysis and grading of aggregate, tests on properties of aggregates.", "Properties of Fresh Concrete: Mixing and batching, workability, factors effecting workability, various test procedures, segregation and bleeding, vibration of concrete, types of vibrators and their influence on composition, analysis of fresh concrete."] },
      { "name": "UNIT - II", "topics": ["Properties of Hardened Concrete: Strength of concrete, water-cement ratio, Gel space ratio, effective water in the mix, short term and long term properties of concrete, test and procedure, influence of various parameters on strength of concrete, relationship between various mechanical strengths of concrete, curing of concrete, maturity concept, influence of temperature on strength of concrete, stress-strain curves for concrete, durability of concrete.", "Strength of Concrete - Shrinkage and temperature effects - creep of concrete - permeability of concrete - durability of concrete - Corrosion - Causes and effects - remedial measures- Thermal properties of concrete - Micro cracking of concrete."] },
      { "name": "UNIT - III", "topics": ["Mix Design of Concrete: A basic consideration, process of mix design, factors influencing mix proportions-mix design by ACI method and IS code method, design of high strength concrete, quality control, various methods of mix design, IS code method, British and ACI methods."] },
      { "name": "UNIT - IV", "topics": ["Admixtures used in Concrete: Classification of admixtures. Chemical and mineral admixtures. Influence of various admixtures on properties of concrete. Admixtures used in preparation of self compacting concrete. Applications, concept of ready mix concrete, fly ash concrete-properties and proportion of fly ash, applications, silica fume, rice husk ash concrete."] },
      { "name": "UNIT - V", "topics": ["Special Concrete: High strength concrete, ferrocement mass concrete, light weight concrete, high density concrete, poly-polymer modified concrete, pre-stressed concrete, self-consolidating concrete, cellular concrete, nano concrete, recycled aggregate concrete, geo polymer concrete, their specialties and applications, Fibre reinforced concrete: Need for fibre reinforced concrete (FRC), Mechanism of FRC, types of Fibres, Fibre shotcrete."] }
    ]
  },
  {
    "code": "MC 3107 CE",
    "title": "Disaster Management",
    "units": [
      { "name": "UNIT I: INTRODUCTION TO DISASTER", "topics": ["Understanding the Concepts, Definitions and Terminologies used in the field of Disaster Management (i.e. Hazard, Risk, Vulnerability, Resilience, and Capacity Building).", "Differential impacts of Disasters in terms of Gender, Age, Social Status, Location, Prosperity, Disabilities.", "Disaster- Development Nexus."] },
      { "name": "UNIT II: TYPES OF HAZARDS AND EMERGING TRENDS", "topics": ["Classification, Causes, Consequences and Controls of", "I) Geophysical hazards-Earthquakes, Landslides, Tsunami", "II) Weather related hazards- Meteorological (Cyclones, Storm-surge and Lighting) Hydrological (Floods, Droughts, Avalanches) Climatological (Wildfire, Cold & Heat Waves)", "III) Biological hazards-Epidemic & Pandemics,", "IV) Technological hazards-Chemical, Industrial, Nuclear", "V) Man-made hazards-Structural Failure, Fire, Transportation accidents, Terrorism and Wars", "Emerging Disasters- Urban Areas, Climate Change.", "Regional and Global Trends-loss of life & Property in various hazards"] },
      { "name": "UNIT III: DISASTER MANAGEMENT CYCLE AND INTERNATIONAL FRAMEWORK", "topics": ["Disaster Management Cycle", "Pre-Disaster – Risk Assessment and Analysis, Risk Mapping, zonation and Microzonation, Prevention and Mitigation of Disasters, Early Warning System; Preparedness, Capacity Development; Awareness", "During Disaster – Evacuation – Disaster Communication – Search and Rescue– Emergency Operation Centre – Incident Command System – Relief and Rehabilitation –", "Post-disaster – Damage and Needs Assessment, Restoration of Critical Infrastructure – Early Recovery – Reconstruction and Redevelopment", "Paradigm Shift in Disaster Management: International Decade for Natural Disaster Reduction; Yokohama Strategy; Hyogo Framework of Action"] },
      { "name": "UNIT IV: DISASTER RISK MANAGEMENT IN INDIA", "topics": ["Disaster Profile of India – Mega Disasters of India and Lessons Learnt", "Disaster Management Act 2005 – Institutional and Financial Mechanism", "National Policy on Disaster Management,", "National Guidelines and Plans on Disaster Management;", "Role of Government (local, state and national),Non-Government and Inter-governmental Agencies"] },
      { "name": "UNIT V: TECHNOLOGICAL APPROACHES TO DISASTER RISK REDUCTION", "topics": ["Geo-informatics in Disaster Management (RS, GIS, GPS and RS)", "Disaster Communication System (Early Warning and Its Dissemination)", "Land Use Planning and Development Regulations", "Disaster Safe Designs and Constructions", "Structural and Non Structural Mitigation of Disasters", "Science &Technology Institutions for Disaster Management in India"] }
    ]
  }
];
